// One row per real buyer question. The answer is the quotable 40 word version; detail carries the rest.
// This is the typed seed for the question bank. When it outgrows a file, the same shape moves to Supabase (see supabase/answers.sql).
export type Answer = {
  slug: string;
  question: string;
  answer: string;
  detail: string;
  audience: "life-science" | "healthcare" | "startup" | "all";
  tier?: "baseline" | "catalyst" | "kinetic" | "critical-mass" | "protocol";
  related: { label: string; href: string }[];
  author: "george-stoff" | "kristen-coughlin";
  dateModified: string;
};

const d = "2026-09-04";
const pricing = { label: "Pricing", href: "/pricing" };
const protocol = { label: "Protocol", href: "/protocol" };

export const answers: Answer[] = [
  // Cost and pricing
  { slug: "how-much-does-a-life-science-marketing-agency-cost", question: "How much does a life science marketing agency cost per month?", answer: "Published life science agency retainers run $8,000 to $15,000 a month. ISOVERTIC starts at $2,500 for a content program and $10,000 for the full pipeline with an outbound seat and a meeting number in writing.", detail: "Most agencies in the category quote by conversation. Ours is on the pricing page in four tiers, plus add ons for MLR review and programmatic page expansion, so a CRO or tools company can put the number in a budget before a call.", audience: "life-science", tier: "catalyst", related: [pricing, { label: "How much does outsourced sales and marketing cost", href: "/field-notes/outsourced-sales-marketing-cost" }], author: "george-stoff", dateModified: d },
  { slug: "how-much-does-healthcare-marketing-cost-for-a-practice", question: "How much should a medical practice spend on marketing?", answer: "A single location practice with a competitive service line runs $5,000 a month in fees plus $3,000 to $10,000 in ad spend. Multi location groups spend $10,000 plus in fees and $10,000 to $50,000 in media.", detail: "The fee buys the site, the content, and a person reading the ads account weekly. The spend buys the patients. Practices under those numbers should start with content at $2,500 and a HIPAA covered intake stack before buying any ads.", audience: "healthcare", tier: "catalyst", related: [pricing, { label: "Healthcare", href: "/industries/healthcare" }], author: "george-stoff", dateModified: d },
  { slug: "what-does-appointment-setting-cost", question: "What does B2B appointment setting cost in 2026?", answer: "Flat retainers run $3,000 to $8,000 a month. Performance models run $150 to $800 per meeting. Dedicated senior teams run $10,000 to $25,000. ISOVERTIC includes one outbound seat with a written meeting number in Kinetic at $10,000.", detail: "The number to compare is cost per qualified held meeting, not the retainer. A $6,000 program producing six meetings costs $1,000 each; producing two, it costs $3,000 each. Ask any vendor for the meeting number in writing before comparing price.", audience: "all", tier: "kinetic", related: [{ label: "Appointment setting", href: "/outbound-appointment-setting" }, pricing], author: "george-stoff", dateModified: d },
  { slug: "is-the-website-included-in-the-monthly-fee", question: "Is the website build included in the monthly fee?", answer: "On a 12 month term, yes, at every tier, along with hosting. Month to month, the build is $15,000 up front. The term also costs what ten months cost month to month, so it is two months free plus the site. You own the code and domain either way.", detail: "The build is a full move onto our stack: Next.js, server rendered, schema on every page. If a term ends early, the unbilled balance of the build is due on the final invoice, prorated to the months served.", audience: "all", related: [pricing, { label: "Web development", href: "/web-development" }], author: "george-stoff", dateModified: d },
  { slug: "can-we-cancel-a-marketing-agency-contract", question: "Can we cancel after the 90 day ramp?", answer: "Yes. Every ISOVERTIC tier runs month to month after the 90 day ramp. No long term contract is required. A 12 month term is optional: it costs what ten months cost month to month and includes the $15,000 website build.", detail: "The ramp has deliverables in writing and, at Kinetic and above, a meeting number. If we are not producing the number we wrote down, you should not be paying us, and the month to month structure makes that a decision, not a negotiation.", audience: "all", related: [pricing, { label: "How it works", href: "/how-it-works" }], author: "george-stoff", dateModified: d },
  { slug: "what-is-the-minimum-ad-spend", question: "What is the minimum ad spend to run Google Ads for a B2B or healthcare company?", answer: "Plan $3,000 a month as a floor for one campaign against commercial intent terms, $10,000 for multiple campaigns with A/B testing. Below $3,000 the campaign cannot exit learning fast enough to be read weekly.", detail: "Spend goes to Google in your own account, which you own. Fees pay the team. Catalyst runs one campaign; Kinetic runs several with landing pages per audience and the search term report read weekly by a person.", audience: "all", tier: "catalyst", related: [{ label: "Google Ads", href: "/google-ads" }, pricing], author: "george-stoff", dateModified: d },
  { slug: "how-much-does-ctv-advertising-cost-for-a-regional-business", question: "How much does connected TV advertising cost for a regional business?", answer: "Connected TV clears at a blended $26 per thousand impressions in 2026, per Adwave, with most campaigns at $25 to $35. A meaningful local test is $10,000 to $15,000 a month in media for 8 to 12 weeks.", detail: "Managed service platforms add 10 to 20 percent on top of media. Our Critical Mass tier carries a $25,000 monthly media minimum spent in your own accounts, with an exposed versus control measurement plan in the agreement.", audience: "healthcare", tier: "critical-mass", related: [{ label: "TV and CTV", href: "/tv-ctv-advertising" }, { label: "CTV playbook", href: "/field-notes/ctv-advertising-small-business" }], author: "george-stoff", dateModified: d },
  { slug: "what-is-the-difference-between-baseline-and-catalyst", question: "What is the difference between the Baseline and Catalyst tiers?", answer: "Baseline, $2,500, is content only: a newsletter, a blog post, eight social posts, and a report each month. Catalyst, $5,000 plus ad spend, doubles the social and adds one Google Ads campaign, a landing page, lead follow up, and a monthly call.", detail: "Baseline runs step two of the system, Rank. Catalyst runs steps one through three. The difference is paid demand and a human on the account every month rather than a report.", audience: "all", tier: "catalyst", related: [pricing, { label: "How it works", href: "/how-it-works" }], author: "george-stoff", dateModified: d },
  { slug: "do-you-offer-a-discount-for-multiple-brands", question: "Do you discount when we run more than one brand?", answer: "Yes. The first brand pays the tier price. Every additional brand on the same tier is 15 percent off, and every brand gets its own report, its own accounts, and its own number.", detail: "Multi brand programs usually land on Critical Mass, which runs the full system per brand with two outbound seats and TV. Two brands on Kinetic is also common for a company with a research and a clinical product line.", audience: "all", tier: "critical-mass", related: [pricing], author: "george-stoff", dateModified: d },

  // Life science and CRO
  { slug: "how-do-researchers-find-a-cro", question: "How do researchers find a CRO or a mouse model provider?", answer: "They search for the specific model, strain, or service before they email anyone, then compare two or three providers on their websites. BioInformatics reports scientists complete 60 percent or more of the buying process before contacting a rep.", detail: "The page that wins is the one that answers the technical question the PI typed: the targeting strategy, the turnaround, the validation data. A 12 page brochure site is eliminated before the email is sent.", audience: "life-science", tier: "baseline", related: [{ label: "How to market a CRO", href: "/field-notes/how-to-market-a-cro-without-a-sales-team" }, { label: "Biotech", href: "/industries/biotech" }], author: "kristen-coughlin", dateModified: d },
  { slug: "who-is-the-buyer-in-an-academic-lab", question: "Who actually buys in an academic lab, the PI or the lab manager?", answer: "For purchases under roughly $50,000, the lab manager or core facility director handles vendors, compares quotes, and places the order. The PI approves. Outbound to lab managers gets read; outbound to PIs with no context gets deleted.", detail: "Sequences that reference the lab's recent publication and the model it implies land. Timing matters too: outreach converts in the months after grant notices go out, when the money is real and the timeline is short.", audience: "life-science", tier: "kinetic", related: [{ label: "Appointment setting", href: "/outbound-appointment-setting" }, { label: "How to market a CRO", href: "/field-notes/how-to-market-a-cro-without-a-sales-team" }], author: "kristen-coughlin", dateModified: d },
  { slug: "what-is-programmatic-seo-for-life-science", question: "What is programmatic SEO for a life science company?", answer: "One server rendered page per entity a researcher might search for, model type, application, strategy, species, each backed by real data and schema markup. For one client that meant 147 pages against a single model architecture.", detail: "It works because researchers search specifically and AI engines cite pages that answer one question completely. Our programmatic page expansion add on ships 50 entity pages at a time for $2,500 a month.", audience: "life-science", tier: "kinetic", related: [{ label: "SEO and content", href: "/seo-content" }, { label: "Getting cited by AI search", href: "/field-notes/how-to-get-cited-by-ai-search" }], author: "george-stoff", dateModified: d },
  { slug: "does-a-cro-need-mlr-review", question: "Does a CRO or research tools company need MLR review on its marketing?", answer: "Not the pharma version. But any claim about preclinical efficacy, a translational outcome, or a clinical result wants a named scientific reviewer and a sign off log before it publishes. Most CRO content, methods and turnaround, skips the gate.", detail: "We build it as a review gate with a claim library so 80 percent of a post is pre approved language and the reviewer sees only new claims once a week. It costs $500 to $1,200 a month depending on tier.", audience: "life-science", related: [{ label: "MLR review workflow", href: "/field-notes/mlr-review-for-marketing-content" }, { label: "Glossary: MLR", href: "/glossary/mlr-review" }], author: "kristen-coughlin", dateModified: d },
  { slug: "when-should-a-cro-start-outbound", question: "When should a CRO start outbound sales instead of relying on referrals?", answer: "When new business still comes from PIs who trained in the same two labs, and revenue tracks the grant calendar. Usually around $3 million. Before that, content and a site that carries the technical comparison return more per dollar.", detail: "Outbound for a CRO is one seat to lab managers with a meeting number in writing, on Kinetic at $10,000. Someone on your side with scientific credibility has to take the meeting.", audience: "life-science", tier: "kinetic", related: [{ label: "How to market a CRO", href: "/field-notes/how-to-market-a-cro-without-a-sales-team" }, pricing], author: "kristen-coughlin", dateModified: d },
  { slug: "how-do-i-market-a-diagnostics-startup", question: "How do you market a diagnostics startup before it has a sales team?", answer: "Publish the validation data and the intended use as pages a clinician or a lab director can find, run one Google Ads campaign against the test name and indication, and hold outbound until someone on your side can take the meeting.", detail: "Pre revenue, Baseline gives the company a voice at $2,500. With a seed budget, Catalyst adds paid demand and a landing page per audience. Any claim about performance goes through the review gate first.", audience: "startup", tier: "catalyst", related: [{ label: "Startups", href: "/industries/startups" }, pricing], author: "george-stoff", dateModified: d },
  { slug: "what-content-should-a-biotech-publish-monthly", question: "What content should a small biotech publish every month?", answer: "One technical post that answers a question a researcher types, one newsletter to your own list, and eight social posts that show the lab rather than stock photos. That is the Baseline cadence and it is enough to be found and cited.", detail: "The post gets a question in the title and the answer in the first 40 words. The newsletter repeats the answer to people who already trust you. Social carries the founder's voice, because personal accounts reach several times what company pages do.", audience: "life-science", tier: "baseline", related: [pricing, { label: "SEO and content", href: "/seo-content" }], author: "kristen-coughlin", dateModified: d },

  // Healthcare and HIPAA
  { slug: "is-a-website-contact-form-hipaa-compliant", question: "Is a standard website contact form HIPAA compliant for a medical practice?", answer: "Usually not. A name plus a condition or a treatment request is protected health information, so the form tool, the email that delivers it, and the CRM that stores it each need a business associate agreement. Most form builders will not sign one.", detail: "The fix is a form that posts to a BAA covered backend with only a link in the notification email, consent text on the form, and no third party pixels on the page. That is our HIPAA form and call stack add on at $750 a month.", audience: "healthcare", related: [{ label: "HIPAA compliant lead generation", href: "/field-notes/hipaa-compliant-lead-generation" }, { label: "Glossary: BAA", href: "/glossary/business-associate-agreement" }], author: "george-stoff", dateModified: d },
  { slug: "can-a-medical-practice-use-the-meta-pixel", question: "Can a medical practice use the Meta pixel or Google Analytics on its website?", answer: "On a blog post, arguably, after the June 2024 court ruling. On any page where a patient can book, request a consult, or log in, no, unless the vendor has signed a business associate agreement, which Meta and Google do not for those tools.", detail: "In American Hospital Association v. Becerra the court vacated HHS guidance about IP addresses on public condition pages; it left the rest intact. Settlements over pixels on booking flows have run $6.6 million to $18.4 million.", audience: "healthcare", related: [{ label: "HIPAA compliant lead generation", href: "/field-notes/hipaa-compliant-lead-generation" }], author: "george-stoff", dateModified: d },
  { slug: "how-do-you-track-google-ads-conversions-under-hipaa", question: "How do you track Google Ads conversions for a practice without violating HIPAA?", answer: "Server side. The form posts to a BAA covered system, and that system tells the ad platform a conversion happened with a click identifier and nothing about the person. No pixel fires on the thank you page.", detail: "You still get cost per booked consultation by campaign. What you give up is remarketing lists built from patients, which you should not have anyway. Call tracking follows the same rule: a vendor under BAA and spoken consent before recording.", audience: "healthcare", tier: "catalyst", related: [{ label: "Google Ads", href: "/google-ads" }, { label: "HIPAA compliant lead generation", href: "/field-notes/hipaa-compliant-lead-generation" }], author: "george-stoff", dateModified: d },
  { slug: "what-is-legitscript-certification", question: "What is LegitScript certification and does my practice need it to run ads?", answer: "LegitScript is a third party certification Google and Meta require before running ads in restricted healthcare categories, including addiction treatment and some telehealth and pharmacy services. Without it the ad account will not serve those ads.", detail: "The application takes weeks and stalls most agencies for months. Ask any vendor which accounts they have carried through certification, by name. We scope the category rules before committing to any numbers.", audience: "healthcare", related: [{ label: "Google Ads", href: "/google-ads" }, { label: "Glossary: LegitScript", href: "/glossary/legitscript" }], author: "george-stoff", dateModified: d },
  { slug: "how-does-a-practice-get-more-referrals-from-physicians", question: "How does a specialty practice get more referrals from other physicians?", answer: "Treat referring physicians as an outbound market: a list of the practices whose patients you want, a sequence that names the condition and the outcome data, and a scheduled call. One seat working that list books meetings the same way it does for any B2B buyer.", detail: "Kinetic includes that seat with a meeting number in writing. The site has to carry clinician forward pages and outcome data first, or the referral coordinator looks you up and finds a brochure.", audience: "healthcare", tier: "kinetic", related: [{ label: "Healthcare", href: "/industries/healthcare" }, { label: "Appointment setting", href: "/outbound-appointment-setting" }], author: "george-stoff", dateModified: d },
  { slug: "what-is-service-line-seo", question: "What is service line SEO for a healthcare practice?", answer: "One hub page per service line with spoke pages for symptoms, treatment, recovery, and referral, each matched to a Google Ads ad group. For one client that was a seven page concussion program hub built ad group by ad group.", detail: "It works because patients search the symptom before the practice. Every service line in a group can run this way, and the structure is what AI search pulls from when someone asks the symptom question.", audience: "healthcare", tier: "catalyst", related: [{ label: "Healthcare", href: "/industries/healthcare" }, { label: "SEO and content", href: "/seo-content" }], author: "george-stoff", dateModified: d },
  { slug: "can-you-run-tv-ads-for-a-medical-practice", question: "Can a regional medical group afford TV advertising?", answer: "Yes, on streaming. Connected TV can be bought by ZIP code at roughly $26 per thousand impressions. A three location group with a reputation driven service line tests at $10,000 to $15,000 a month for 8 to 12 weeks in its best market.", detail: "The spot is promotional content, so any outcome claim goes through medical review and the landing page needs a BAA covered form. We run it on Critical Mass with a $25,000 monthly media minimum and an exposed versus control plan.", audience: "healthcare", tier: "critical-mass", related: [{ label: "TV and CTV", href: "/tv-ctv-advertising" }], author: "george-stoff", dateModified: d },

  // MLR and compliance
  { slug: "how-long-does-mlr-review-take", question: "How long does MLR review take?", answer: "Vodori's 2025 benchmark puts the average job at 14.8 days from submission to approval. At mid size and large pharma, Indegene reports 50 to 60 days per piece. A small company with one named reviewer and a claim library can run it weekly.", detail: "The slow version routes whole drafts over email to a committee. The weekly version flags only new claims, attaches the reference, and asks one question: approved, revised, or cut.", audience: "life-science", related: [{ label: "MLR review workflow", href: "/field-notes/mlr-review-for-marketing-content" }, { label: "Glossary: MLR", href: "/glossary/mlr-review" }], author: "george-stoff", dateModified: d },
  { slug: "what-is-a-claim-library", question: "What is a claim library in medical marketing?", answer: "A list of every clinical, safety, or efficacy statement a company is allowed to make, each with its reference, approved once. Content is written from the library so most of a piece is pre approved language and the reviewer sees only what is new.", detail: "Building it from your existing approved materials is the setup work in our MLR review gate add on. It is also what you hand a new agency or a new hire on day one.", audience: "life-science", related: [{ label: "MLR review workflow", href: "/field-notes/mlr-review-for-marketing-content" }], author: "george-stoff", dateModified: d },
  { slug: "do-social-posts-need-mlr-review", question: "Do social media posts need MLR review?", answer: "Only the ones that make a clinical, safety, or efficacy claim. A founder story, a hiring post, a conference recap, or a photo of the lab does not. Batch the ones that do into the weekly review with the blog post.", detail: "Most social content skips the gate, which is why a regulated company can still publish eight or sixteen posts a month. The claim library makes the ones that need review fast.", audience: "life-science", related: [{ label: "MLR review workflow", href: "/field-notes/mlr-review-for-marketing-content" }, pricing], author: "george-stoff", dateModified: d },
  { slug: "who-should-be-the-medical-reviewer", question: "Who should be the medical reviewer for a small company's content?", answer: "Someone with an MD or PhD credential who is accountable to you: a medical director, a scientific founder, or a contracted reviewer you name. We build the workflow around that person. We do not supply the reviewer, on purpose.", detail: "The person signing off on your claims should answer to your company, not your agency. One reviewer hour a week supports a newsletter, a post, and a month of social when only new claims are flagged.", audience: "life-science", related: [{ label: "MLR review workflow", href: "/field-notes/mlr-review-for-marketing-content" }], author: "kristen-coughlin", dateModified: d },

  // Startups
  { slug: "should-a-startup-hire-a-marketer-or-an-agency-first", question: "Should a seed stage startup hire a marketer or an agency first?", answer: "Neither, until the site says something. Then an agency, because a $130,000 marketing hire inherits an empty demand environment and a $2,500 to $5,000 program buys the site, the content, and the campaign that the eventual hire will run.", detail: "Kinetic at $10,000 replaces the first marketing hire and the first SDR until a Series A supports payroll. Past $10 million in revenue, hire leadership and inherit the documented system.", audience: "startup", tier: "catalyst", related: [{ label: "Startups", href: "/industries/startups" }, { label: "Hire or outsource", href: "/field-notes/hire-salesperson-or-outsource" }], author: "george-stoff", dateModified: d },
  { slug: "how-do-i-show-pipeline-to-my-board", question: "How do I show pipeline progress to a board before we have a sales team?", answer: "With a 90 day ramp that has deliverables in writing: pages live, campaigns running at a stated cost per lead, and at Kinetic a meeting number. Paste the agreement into the board update and report against it monthly.", detail: "A board wants a number that was committed to before it was hit. That is why every tier states its deliverables in the agreement and why we publish pricing so the cost line is in the model from day one.", audience: "startup", tier: "kinetic", related: [{ label: "Startups", href: "/industries/startups" }, { label: "How it works", href: "/how-it-works" }], author: "george-stoff", dateModified: d },
  { slug: "can-we-pause-marketing-between-funding-rounds", question: "Can we pause the program between funding rounds?", answer: "Yes. After the 90 day ramp the engagement is month to month, so a startup can pause between raises and restart without a new contract. The exception is a 12 month term taken to include the website build.", detail: "Pausing paid demand is cheap. Pausing content costs more than it saves, because search and AI visibility compound and restart slowly. Most startups keep Baseline running through a raise.", audience: "startup", tier: "baseline", related: [pricing, { label: "Startups", href: "/industries/startups" }], author: "george-stoff", dateModified: d },
  { slug: "what-stack-should-a-startup-website-use", question: "What stack should a startup website be built on so engineers do not rip it out later?", answer: "Next.js with TypeScript, server rendered, on Vercel, with content in typed files or a Postgres database. It is what your first engineering hire already knows, it renders fully for crawlers and AI, and you own the code.", detail: "That is the stack every ISOVERTIC build uses. The website build is included on a 12 month term or $15,000 up front, and the repository is yours on day one.", audience: "startup", related: [{ label: "Web development", href: "/web-development" }, pricing], author: "george-stoff", dateModified: d },

  // AI search and SEO
  { slug: "how-do-i-get-my-company-cited-by-chatgpt", question: "How do I get my company cited by ChatGPT and Perplexity?", answer: "Publish one page per question your buyers ask, answer it in the first 40 words with one quotable number, render it on the server so the text is in the HTML, and add schema that names the entity. Then earn mentions on third party sites.", detail: "Ahrefs found only 12 percent of AI cited URLs overlap with Google's top ten, so ranking is not enough. Omniscient Digital found 57 percent of branded citations come from reviews and listicles, not the brand's own site.", audience: "all", tier: "baseline", related: [{ label: "Getting cited by AI search", href: "/field-notes/how-to-get-cited-by-ai-search" }, { label: "SEO and content", href: "/seo-content" }], author: "george-stoff", dateModified: d },
  { slug: "does-ranking-on-google-mean-ai-will-cite-you", question: "If we rank on page one of Google, will AI search cite us too?", answer: "Not reliably. Ahrefs analyzed 15,000 queries and found only 12 percent of URLs cited by AI tools overlap with Google's top ten organic results. Profound found only 11 percent of domains are cited by both ChatGPT and Perplexity.", detail: "The engines choose differently. Perplexity searches live and cites about 22 sources per answer; ChatGPT leans on stable reference sources. Entity pages plus earned third party mentions cover most of the surface.", audience: "all", related: [{ label: "Getting cited by AI search", href: "/field-notes/how-to-get-cited-by-ai-search" }], author: "george-stoff", dateModified: d },
  { slug: "what-is-aeo", question: "What is AEO, answer engine optimization?", answer: "Structuring pages so an AI answer engine can extract and cite them: one question per page, the answer in the first 40 words, a quotable number or definition, server rendered HTML, and schema that names the entity the page is about.", detail: "It overlaps with SEO but rewards different things. Google rewards authority across a site; answer engines reward the single page that answers the question completely, which is why entity pages and question pages outperform long guides.", audience: "all", related: [{ label: "Glossary: AEO", href: "/glossary/answer-engine-optimization" }, { label: "SEO and content", href: "/seo-content" }], author: "george-stoff", dateModified: d },
  { slug: "why-does-server-rendering-matter-for-seo", question: "Why does server rendering matter for SEO and AI search?", answer: "Because a crawler or a model reads the HTML it receives. If the text is assembled by JavaScript in the browser, many crawlers see an empty page. Server rendering puts every word, number, and schema block in the response.", detail: "It is also why animated counters and client rendered tabs hide content. Our stack renders every page on the server and treats animation as an enhancement the static page never depends on.", audience: "all", related: [{ label: "Web development", href: "/web-development" }, { label: "Glossary: server rendering", href: "/glossary/server-rendering" }], author: "george-stoff", dateModified: d },
  { slug: "how-many-pages-does-a-site-need-to-rank", question: "How many pages does a website need to rank for long tail searches?", answer: "As many as there are questions your buyers ask. For one life science client that was 147 pages in a single model architecture. A 12 page site ranks for its brand name; a 150 page site ranks for the category.", detail: "The pages have to be real: one entity or one question each, backed by data, not spun variations. Our programmatic page expansion ships 50 entity pages at a time for $2,500 a month on top of any tier.", audience: "all", tier: "kinetic", related: [{ label: "SEO and content", href: "/seo-content" }, pricing], author: "george-stoff", dateModified: d },

  // Outbound and sales
  { slug: "what-is-a-qualified-meeting", question: "What counts as a qualified meeting in an appointment setting program?", answer: "A held conversation with a person who matches criteria agreed before the program starts, role, company type, and a stated need, confirmed in advance and delivered with a brief on who they are and why they said yes.", detail: "The criteria go in the agreement next to the monthly number. A meeting that no shows or fails the criteria does not count against the commitment, which is why confirmation sequences run before every call.", audience: "all", tier: "kinetic", related: [{ label: "Appointment setting", href: "/outbound-appointment-setting" }, { label: "Lead generation vs appointment setting", href: "/field-notes/lead-generation-vs-appointment-setting" }], author: "george-stoff", dateModified: d },
  { slug: "who-takes-the-sales-meeting", question: "Who takes the sales meeting once you book it?", answer: "Someone on your side. We book it, brief you, and step out. For a technical sale that is usually the founder or a scientific liaison, because founder knowledge closes and prospecting is the part worth renting.", detail: "Our contact form asks this before we quote Kinetic. If the answer is nobody yet, start with Catalyst and paid demand, or the Protocol, and add the outbound seat when there is a closer.", audience: "all", tier: "kinetic", related: [{ label: "Contact", href: "/contact" }, { label: "Hire or outsource", href: "/field-notes/hire-salesperson-or-outsource" }], author: "george-stoff", dateModified: d },
  { slug: "what-reply-rate-should-cold-email-get", question: "What reply rate should cold email get in a technical B2B market?", answer: "Low to mid single digits with a researched list and real personalization. Generic sequences into scientists or clinicians fall to a fraction of a percent. The list and the first sentence decide it more than the length or the tooling.", detail: "For one healthcare revenue client the entire prospect universe was built from federal public use files before a single email went out. Coordinated email, phone, and LinkedIn over weeks converts replies into held meetings.", audience: "all", related: [{ label: "Appointment setting", href: "/outbound-appointment-setting" }, { label: "More B2B sales meetings", href: "/field-notes/how-to-get-more-b2b-sales-meetings" }], author: "george-stoff", dateModified: d },
  { slug: "why-do-marketing-leads-never-get-a-call", question: "Why do most marketing leads never get a sales call?", answer: "Because the handoff between marketing and sales belongs to nobody. More than 70 percent of marketing leads are never contacted by sales at all. A quote request that waits four days is a quote request answered by a competitor.", detail: "The fix costs discipline before it costs money: a response time standard and a written follow up sequence. On Catalyst, leads are worked within one business day; the lead handoff runbook is the fifth runbook in the Protocol.", audience: "all", tier: "catalyst", related: [{ label: "Why your pipeline is inconsistent", href: "/field-notes/why-your-pipeline-is-inconsistent" }, protocol], author: "george-stoff", dateModified: d },

  // Protocol and working with us
  { slug: "what-is-the-protocol", question: "What is the ISOVERTIC Protocol?", answer: "Step six of our system, Educate. One or two days at your office where your team learns the six step system and leaves with our runbooks rewritten in your brand and licensed for internal use. $5,000 for one department, $20,000 for a full team.", detail: "Current clients add the one day version for $3,500. The full team version includes an audit of your process and CRM before we arrive, a developer track, recorded sessions, and 90 days of calls.", audience: "all", tier: "protocol", related: [protocol, pricing], author: "george-stoff", dateModified: d },
  { slug: "can-our-in-house-team-run-your-system", question: "Can our in house marketing team run your system instead of hiring you monthly?", answer: "Yes. That is what the Protocol is for. Your team is taught the system at your office and keeps the eight runbooks in your brand: content production, page build, Google Ads, outbound, lead handoff, reporting, MLR review, and HIPAA rules.", detail: "The runbooks are licensed to one company for internal use, no resale and no redistribution to an agency. Agencies who want to run the system for their clients ask about the agency license.", audience: "all", tier: "protocol", related: [protocol], author: "george-stoff", dateModified: d },
  { slug: "who-works-on-our-account", question: "Who actually works on our account at each tier?", answer: "The founder and the same senior team at every tier. There is no junior tier of staff behind the lower price. Baseline buys fewer steps of the system than Kinetic, not a different team.", detail: "The COO, a molecular biologist with a decade of CRO sales, is on life science accounts. AI runs scheduling, deployment, data collection, and research; people create, design, review, test, and engage.", audience: "all", related: [{ label: "About", href: "/about" }, { label: "How it works", href: "/how-it-works" }], author: "george-stoff", dateModified: d },
  { slug: "do-you-use-ai-to-write-content", question: "Do you use AI to write client content?", answer: "No. AI runs scheduling, deployment, data collection, and research on every account. Humans create, design, review, test, and engage. Every word a buyer reads, every ad a buyer clicks, and every call a buyer takes was made by a person.", detail: "That split is why the floor can be $2,500 a month instead of $8,500, and why a scientist or a clinician reading the content does not hit the phrasing that signals a machine wrote it.", audience: "all", related: [{ label: "How it works", href: "/how-it-works" }, { label: "About", href: "/about" }], author: "george-stoff", dateModified: d },
  { slug: "what-do-we-need-to-provide", question: "What does a client have to provide to start?", answer: "Access to your domain, ad accounts, and CRM, a point of contact who can approve in 48 hours, and, if your content makes clinical claims, a named reviewer with an MD or PhD credential. Roughly two hours a week during the ramp.", detail: "At Kinetic, someone on your side takes the meetings we book. Without those two things, approval speed and a closer, no vendor can make the program work.", audience: "all", related: [{ label: "How it works", href: "/how-it-works" }, { label: "Contact", href: "/contact" }], author: "george-stoff", dateModified: d },
  { slug: "what-happens-in-the-first-90-days", question: "What happens in the first 90 days of an engagement?", answer: "Weeks 1 to 2: onboarding, accounts, the review gate if needed, and the first content calendar. Weeks 3 to 6: publishing live, landing pages and campaigns built, outbound approved. Weeks 7 to 12: weekly optimization, first meetings, a written day 90 review.", detail: "After the ramp the engagement runs month to month unless you took a term for the website. The day 90 review is against the deliverables in your agreement, not against a slide.", audience: "all", related: [{ label: "How it works", href: "/how-it-works" }], author: "george-stoff", dateModified: d },
  { slug: "do-you-work-with-companies-outside-new-york", question: "Do you work with companies outside New York?", answer: "Yes. The office is in Bohemia on Long Island and clients are national. Everything except the Protocol runs remotely. The Protocol is onsite, with travel billed at cost beyond 50 miles for the one day version and included for the full team version.", detail: "Life science clients cluster in Boston, New York, San Diego, and the Research Triangle; healthcare clients are wherever the practice is. Time zones have not been a constraint.", audience: "all", related: [{ label: "Long Island", href: "/long-island" }, protocol], author: "george-stoff", dateModified: d },
  { slug: "why-do-you-publish-pricing", question: "Why does ISOVERTIC publish pricing when other agencies do not?", answer: "Because our buyer is a founder or a scientist who hates a wasted discovery call as much as we do, and because the page that answers the question everyone types and nobody answers is the page that ranks and gets cited.", detail: "Published pricing also changes the call. You already know the number, so thirty minutes goes to your market, your pipeline math, and whether the tier you picked is right.", audience: "all", related: [pricing], author: "george-stoff", dateModified: d },
];

export const getAnswer = (slug: string) => answers.find((a) => a.slug === slug);
