// Copy for the self serve Baseline checkout (/start) and the post checkout intake (/welcome).

export const startCopy = {
  title: "Start Baseline | ISOVERTIC",
  metaDescription: "Sign up for Baseline with a card. Month to month at $3,000, or a 12 month term at $2,500 with two months free and the website rebuild included. No call required.",
  eyebrow: "Start Baseline",
  h1: "Pick a term. Check out. We start this week.",
  lead: "No discovery call. You choose month to month or the 12 month term, pay by card on Stripe, and land on a short intake form. We generate the first content calendar inside five business days and publish from there. A 15 minute call is there if you want one, after you sign up.",
  planLabel: "Billing",
  emailLabel: "Work email",
  agreeLabel: "I agree to the 12 month term. If the term ends early, the unbilled balance of the $15,000 website build is due, prorated to months served.",
  submit: "Continue to secure checkout",
  stripeNote: "Payment runs on Stripe. We never see your card. Your receipt and the intake link arrive by email.",
  whatHappens: [
    "Today: checkout on Stripe, then a ten minute intake form.",
    "Inside five business days: your first content calendar, one newsletter, one post, and eight social posts scheduled for the month.",
    "Every month after: the same cadence, plus a one page report on what it produced.",
    "On the 12 month term: the website rebuild starts inside the first 30 days on our stack, server rendered, schema on every page, hosted for the term at no charge.",
  ],
  error: "A working email is required, and the 12 month term needs the box checked.",
  checkoutError: "Checkout could not start. Email georgestoff@rocketcreative.net and we will send a payment link by hand.",
  planMissing: "Pick a plan on the pricing page first.",
};

export const welcomeCopy = {
  title: "Welcome to Baseline | ISOVERTIC",
  eyebrow: "You are in",
  h1: "Paid. Now tell us what to write about.",
  lead: "Ten minutes here saves a call. Everything below is what our team needs to generate the first content calendar. Skip anything you do not know; we will ask by email.",
  unverified: "We could not verify a completed checkout for this link. If you just paid, wait a minute and refresh. Otherwise start on the pricing page or email georgestoff@rocketcreative.net.",
  fields: {
    company: "Company name",
    website: "Website",
    contactName: "Your name",
    role: "Your role",
    audience: "Who buys from you, in one or two sentences",
    problems: "The three questions your buyers ask most before they buy",
    topics: "Ten topics you could talk about for an hour (one per line)",
    competitors: "Two or three competitors buyers compare you to",
    voice: "Links to two or three pieces that sound like you (emails, posts, pages)",
    social: "Which two social channels should we post to, and the handles",
    newsletter: "Where does your email list live today (Mailchimp, HubSpot, nowhere yet)",
    claims: "Does your content make clinical, safety, or efficacy claims?",
    reviewer: "If yes, who reviews claims (name, credential, email)",
    access: "Access we will need: CMS, social scheduling, email tool. We send a checklist by email; list anything unusual here.",
    call: "Want an optional 15 minute call this week?",
    notes: "Anything else",
  },
  claimsOptions: [
    { value: "", label: "Not sure" },
    { value: "No", label: "No" },
    { value: "Yes", label: "Yes" },
  ],
  callOptions: [
    { value: "No, email is fine", label: "No, email is fine" },
    { value: "Yes, send a calendar link", label: "Yes, send a calendar link" },
  ],
  submit: "Send it and start",
  sending: "Sending",
  error: "Company, website, and your name are required.",
  successTitle: "Received. The first calendar arrives inside five business days.",
  successBody: "You will get an access checklist by email today and the content calendar for approval within five business days. Approve in 48 hours and the first pieces publish the following week.",
  successCall: "You asked for a call. A calendar link is on its way from George.",
};
