// Copy for self serve checkout (/start) and the post checkout intake (/welcome). Prices come from content/tiers.ts through lib/stripe.ts.

export const startCopy = {
  title: "Start Your Tier | ISOVERTIC",
  metaDescription: "Sign up for any tier with a card or a bank debit. Month to month, or a 12 month term with two months free and the $15,000 website rebuild included. Kinetic and Critical Mass run on a 1 year term paid quarterly. No call required.",
  eyebrow: "Start",
  h1: "Pick a tier. Pick a term. Check out.",
  lead: "No discovery call. Choose the tier, then month to month or the 12 month term, and pay by card or bank debit on Stripe. You land on a ten minute intake form, and the first content calendar arrives inside five business days. A 15 minute call is there if you want one, after you sign up.",
  tierLabel: "Tier",
  billingLabel: "Billing",
  emailLabel: "Work email",
  companyLabel: "Company",
  agreeLabel: "I agree to the 12 month term. If the term ends early, the unbilled balance of the $15,000 website build is due, prorated to months served.",
  submit: "Continue to secure checkout",
  stripeNote: "Payment runs on Stripe. Card, Apple Pay, Google Pay, or ACH bank debit. We never see your card or account number. Receipt and the intake link arrive by email.",
  bankNote: "For amounts above $10,000 we recommend the bank debit option on the Stripe page: 0.8 percent capped at $5 per payment instead of a card fee, and no issuer limit. Bank debits take up to four business days to clear and the engagement starts when the first one settles.",
  mediaNote: "Ad spend and media are not in the checkout total. They run in your own ad accounts, which you own.",
  whatHappens: [
    "Today: checkout on Stripe, then a ten minute intake form.",
    "Inside five business days: your first content calendar. On Catalyst and above, the campaign build and landing page start the same week.",
    "Weeks 1 to 2: onboarding, accounts, the review gate if your content needs one. Weeks 3 to 6: publishing live, campaigns and outbound built. Weeks 7 to 12: weekly optimization and the day 90 review against the deliverables in your agreement.",
    "On the 12 month term: the website rebuild starts inside the first 30 days on our stack, server rendered, schema on every page, hosted for the term at no charge.",
  ],
  error: "A working email is required, and the 12 month term needs the box checked.",
  checkoutError: "Checkout could not start. Email sale@isovertic.com and we will send a payment link by hand.",
  planMissing: "Pick a tier on the pricing page first.",
  talkFirst: "Would rather talk first",
};

export const welcomeCopy = {
  title: "Welcome to ISOVERTIC",
  eyebrow: "You are in",
  h1: "Paid. Now tell us what to work on.",
  lead: "Ten minutes here saves a call. Everything below is what our team needs to build the first content calendar and, on Catalyst and above, the first campaign. Skip anything you do not know; we will ask by email.",
  pending: "Your bank debit is processing. It clears in up to four business days and we start the moment it settles. Fill out the intake now so nothing waits on the bank.",
  unverified: "We could not verify a completed checkout for this link. If you just paid, wait a minute and refresh. Otherwise start on the pricing page or email sale@isovertic.com.",
  fields: {
    company: "Company name",
    website: "Website",
    contactName: "Your name",
    role: "Your role",
    audience: "Who buys from you, in one or two sentences",
    problems: "The three questions your buyers ask most before they buy",
    topics: "Ten topics you could talk about for an hour (one per line)",
    competitors: "Two or three competitors buyers compare you to",
    voice: "Links to two or three pieces that sound like you (emails, posts, pages)",
    social: "Which two social channels should we post to, and the handles",
    newsletter: "Where does your email list live today (Mailchimp, HubSpot, nowhere yet)",
    ads: "If your tier runs ads: your Google Ads account ID, or none yet",
    closer: "If your tier books meetings: who takes them on your side",
    claims: "Does your content make clinical, safety, or efficacy claims?",
    reviewer: "If yes, who reviews claims (name, credential, email)",
    access: "Access we will need: CMS, social scheduling, email tool, CRM. We send a checklist by email; list anything unusual here.",
    call: "Want an optional 15 minute call this week?",
    notes: "Anything else",
  },
  claimsOptions: [
    { value: "", label: "Not sure" },
    { value: "No", label: "No" },
    { value: "Yes", label: "Yes" },
  ],
  callOptions: [
    { value: "No, email is fine", label: "No, email is fine" },
    { value: "Yes, send a calendar link", label: "Yes, send a calendar link" },
  ],
  submit: "Send it and start",
  sending: "Sending",
  error: "Company, website, and your name are required.",
  successTitle: "Received. The first calendar arrives inside five business days.",
  successBody: "You will get an access checklist by email today and the content calendar for approval within five business days. Approve in 48 hours and the first pieces publish the following week.",
  successCall: "You asked for a call. A calendar link is on its way from George.",
};
