export type Term = {
  slug: string;
  term: string;
  definition: string; // one or two sentences, quotable
  detail: string;
  related: { label: string; href: string }[];
};

export const glossary: Term[] = [
  { slug: "mlr-review", term: "MLR review", definition: "Medical, legal, and regulatory review: the process a pharma, biotech, device, or diagnostics company uses to check promotional content for supported claims, fair balance, and regulatory compliance before it reaches a clinician or a patient.", detail: "Industry benchmarks put the average review job at 14.8 days and large pharma cycles at 50 to 60 days. A small company runs it weekly with one named reviewer, a claim library, and a sign off log.", related: [{ label: "MLR review workflow", href: "/field-notes/mlr-review-for-marketing-content" }, { label: "How long does MLR review take", href: "/answers/how-long-does-mlr-review-take" }] },
  { slug: "claim-library", term: "Claim library", definition: "A maintained list of every clinical, safety, or efficacy statement a company is permitted to make, each paired with its supporting reference and approved once, so new content is written from pre approved language.", detail: "The library is the setup work in a review gate. It cuts review to the new claims only and is what a company hands a new agency or hire on day one.", related: [{ label: "What is a claim library", href: "/answers/what-is-a-claim-library" }] },
  { slug: "business-associate-agreement", term: "Business associate agreement (BAA)", definition: "A contract required by HIPAA between a covered entity and any vendor that creates, receives, stores, or transmits protected health information on its behalf, making the vendor liable for safeguarding it.", detail: "Form tools, email platforms, CRMs, and call recording vendors that touch patient inquiries all need one. Most consumer form builders and ad pixels will not sign one, which is why they cannot sit on a booking page.", related: [{ label: "HIPAA compliant lead generation", href: "/field-notes/hipaa-compliant-lead-generation" }, { label: "Is a contact form HIPAA compliant", href: "/answers/is-a-website-contact-form-hipaa-compliant" }] },
  { slug: "protected-health-information", term: "Protected health information (PHI)", definition: "Any individually identifiable health information held or transmitted by a HIPAA covered entity or its business associates, including a name or contact detail combined with a condition, treatment, or appointment request.", detail: "On a marketing site, a consult request form for a named procedure produces PHI the moment it is submitted. A June 2024 court ruling narrowed HHS guidance on IP addresses on public pages but left the rest intact.", related: [{ label: "HIPAA compliant lead generation", href: "/field-notes/hipaa-compliant-lead-generation" }] },
  { slug: "legitscript", term: "LegitScript certification", definition: "A third party certification that Google and Meta require before running ads in restricted healthcare categories such as addiction treatment and certain telehealth and pharmacy services.", detail: "Applications take weeks and stall agencies unfamiliar with the process for months. Category rules should be scoped before any campaign number is committed to.", related: [{ label: "What is LegitScript", href: "/answers/what-is-legitscript-certification" }, { label: "Google Ads", href: "/google-ads" }] },
  { slug: "answer-engine-optimization", term: "Answer engine optimization (AEO)", definition: "Structuring pages so AI answer engines such as ChatGPT, Perplexity, and Google AI Mode can extract and cite them: one question per page, the answer in the first 40 words, a quotable figure, server rendered HTML, and entity schema.", detail: "Only about 12 percent of AI cited URLs overlap with Google's top ten organic results, so AEO is a separate discipline from ranking, with entity pages and third party mentions doing most of the work.", related: [{ label: "Getting cited by AI search", href: "/field-notes/how-to-get-cited-by-ai-search" }, { label: "What is AEO", href: "/answers/what-is-aeo" }] },
  { slug: "server-rendering", term: "Server rendering", definition: "Generating a page's full HTML on the server before it is sent, so every word, number, and schema block is present in the response without the browser running JavaScript.", detail: "Crawlers and AI models read what the server returns. Client rendered content, animated counters, and tabs assembled in the browser are often invisible to them.", related: [{ label: "Why server rendering matters", href: "/answers/why-does-server-rendering-matter-for-seo" }, { label: "Web development", href: "/web-development" }] },
  { slug: "entity-page", term: "Entity page", definition: "A single page dedicated to one thing a buyer might search for, a model type, a service, a term, a location, backed by real data and marked up with schema that names the entity.", detail: "Entity pages are the unit of programmatic SEO and the format AI engines cite most readily, because each answers one question completely. A 147 page life science site is 147 entity pages.", related: [{ label: "Programmatic SEO for life science", href: "/answers/what-is-programmatic-seo-for-life-science" }] },
  { slug: "programmatic-seo", term: "Programmatic SEO", definition: "Building large sets of entity pages from a structured data source, each server rendered and schema marked, rather than writing pages one at a time by hand.", detail: "It works when every page is backed by a real data atom and fails when pages are spun variations of one another. Our add on ships 50 entity pages at a time.", related: [{ label: "SEO and content", href: "/seo-content" }, { label: "Pricing", href: "/pricing" }] },
  { slug: "schema-markup", term: "Schema markup", definition: "Structured data added to a page in JSON LD that tells search engines and AI models what the page is about: an organization, a person, a service, a question and its answer, a defined term.", detail: "Every ISOVERTIC page carries it through one set of builders so nothing drifts. It is how a Person page becomes an author entity and how a question page becomes citable.", related: [{ label: "Web development", href: "/web-development" }] },
  { slug: "qualified-meeting", term: "Qualified meeting", definition: "A held conversation with a person who matches criteria agreed before an outbound program starts, role, company type, and stated need, confirmed in advance and delivered with a brief.", detail: "The criteria and the monthly number both go in the agreement. No shows and meetings that fail criteria do not count against the commitment.", related: [{ label: "What counts as a qualified meeting", href: "/answers/what-is-a-qualified-meeting" }, { label: "Appointment setting", href: "/outbound-appointment-setting" }] },
  { slug: "cost-per-meeting", term: "Cost per meeting", definition: "Total program cost divided by the number of qualified held meetings it produced in the period. The number that lets you compare a $6,000 outbound retainer to a $10,000 full pipeline tier.", detail: "A $10,000 program producing ten meetings costs $1,000 each; producing three, $3,333. A vendor who will not commit to a meeting number will not let you calculate it.", related: [{ label: "Outsourced sales and marketing cost", href: "/field-notes/outsourced-sales-marketing-cost" }] },
  { slug: "the-seam", term: "The seam", definition: "The handoff between marketing and sales where leads are lost because no one owns it. More than 70 percent of marketing leads are never contacted by sales at all.", detail: "Owning the seam means a response time standard and a written follow up sequence. It is the cheapest pipeline most companies never buy.", related: [{ label: "Why your pipeline is inconsistent", href: "/field-notes/why-your-pipeline-is-inconsistent" }] },
  { slug: "connected-tv", term: "Connected TV (CTV)", definition: "Television advertising delivered through streaming services on internet connected TVs, bought programmatically against geography and audience with a frequency cap and a completion rate you can read the next day.", detail: "Blended 2026 CPMs run about $26 per thousand impressions. A regional business can test at $10,000 to $15,000 a month; our Critical Mass tier carries a $25,000 monthly media minimum.", related: [{ label: "TV and CTV", href: "/tv-ctv-advertising" }, { label: "CTV playbook", href: "/field-notes/ctv-advertising-small-business" }] },
  { slug: "exposed-versus-control", term: "Exposed versus control", definition: "A measurement plan for TV and media in which a matched geography receives no ads and the difference in branded search, direct traffic, and booked consultations between exposed and control markets is read as the effect.", detail: "It is the only honest way to measure a channel last touch attribution was never built for. We write it into the agreement before the media buy.", related: [{ label: "TV and CTV", href: "/tv-ctv-advertising" }] },
  { slug: "runbook", term: "Runbook", definition: "A written, step by step operating procedure for one recurring job, content production, a Google Ads weekly review, an outbound sequence, so the job runs the same way whoever runs it.", detail: "ISOVERTIC operates from eight runbooks and hands them over, rewritten in the client's brand, as step six of the system, the Protocol.", related: [{ label: "Protocol", href: "/protocol" }] },
  { slug: "the-90-day-ramp", term: "The 90 day ramp", definition: "The first three months of an engagement, with deliverables stated in the agreement and, at Kinetic and above, a monthly meeting number in writing, reviewed on day 90 against actuals.", detail: "After the ramp the engagement runs month to month. The ramp is what makes the commitment a decision rather than a renegotiation.", related: [{ label: "How it works", href: "/how-it-works" }, { label: "What happens in the first 90 days", href: "/answers/what-happens-in-the-first-90-days" }] },
  { slug: "conditional-knockout", term: "Conditional knockout", definition: "A genetically engineered mouse model in which a gene is deleted only in specific tissues or at a chosen time, typically using Cre recombinase and loxP sites, so the effect of the gene can be studied without the lethality of a whole body deletion.", detail: "It is one of the most searched model types by researchers and one of the entity pages a CRO's site has to carry in depth to be found and cited.", related: [{ label: "How to market a CRO", href: "/field-notes/how-to-market-a-cro-without-a-sales-team" }, { label: "Biotech", href: "/industries/biotech" }] },
];

export const getTerm = (slug: string) => glossary.find((t) => t.slug === slug);
