export const site = {
  name: "ISOVERTIC",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://isovertic.com",
  description:
    "The growth agency for companies that sell to specialists: scientists, startups, and healthcare brands. One senior team owns the pipeline from the first search to the booked meeting, from a $2,500 content program to the full pipeline. You close.",
  locality: "Long Island, New York",
  founder: "George Stoff",
  linkedin: "https://www.linkedin.com/in/george-stoff-b1826971",
  entity: "ISOVERTIC is an assumed name of Rocket Creative LLC.",
  complianceLine: "ISOVERTIC is not a covered entity. We operate as a business associate for covered entity clients under executed Business Associate Agreements.",
  legalName: "Rocket Creative LLC",
  address: { street: "600 Johnson Ave, Suite D5", locality: "Bohemia", region: "NY", postalCode: "11716", country: "US" },
  phone: "+1-631-816-9577",
  email: "sale@isovertic.com",
  knowsAbout: [
    "Life science marketing",
    "CRO marketing",
    "Healthcare marketing",
    "HIPAA compliant lead generation",
    "MLR review workflow",
    "B2B appointment setting",
    "Google Ads management",
    "Connected TV advertising",
    "SEO",
    "AI search optimization",
    "Next.js web development",
  ],
};
