export const site = {
  name: "ISOVERTIC",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://isovertic.com",
  description:
    "One senior team runs a six step growth system for scientists, startups, and healthcare brands, from a $2,500 content program to a full pipeline that books meetings on your calendar. You close.",
  locality: "Long Island, New York",
  founder: "George Stoff",
  linkedin: "https://www.linkedin.com/in/george-stoff-b1826971",
  entity: "ISOVERTIC is an assumed name of Rocket Creative LLC.",
  legalName: "Rocket Creative LLC",
  address: { street: "600 Johnson Ave, Suite D5", locality: "Bohemia", region: "NY", postalCode: "11716", country: "US" },
  phone: "+1-631-816-9577",
  email: "georgestoff@rocketcreative.net",
  knowsAbout: [
    "Life science marketing",
    "CRO marketing",
    "Healthcare marketing",
    "HIPAA compliant lead generation",
    "MLR review workflow",
    "B2B appointment setting",
    "Google Ads management",
    "Connected TV advertising",
    "SEO",
    "AI search optimization",
    "Next.js web development",
  ],
};
